tenant: public
namespace: default
name: user-transform-new-14
className: com.bridge.data.TransformUser
inputs:
  - "persistent://public/default/debezium.public.users"
output: "persistent://public/default/debezium.public.users-public"
jar: "transform-function-v1.jar"
parallelism: 1
retainOrdering: true
