tenant: public
namespace: default
name: user-transform-new-11
className: com.bridge.data.TransformUserMessage
inputs:
  - "persistent://public/default/debezium.public.users"
customSerdeInputs:
  "persistent://public/default/debezium.public.users": com.bridge.data.UserMessageSerDe
output: "persistent://public/default/debezium.public.users-public"
outputSerdeClassName: com.bridge.data.PublicUserSerDe
jar: "transform-function-v1.jar"
parallelism: 1
retainOrdering: true
