tenant: public
namespace: default
name: user-transform-new-13
className: com.bridge.data.TransformStringMessage
inputs:
  - "persistent://public/default/debezium.public.users"
output: "persistent://public/default/debezium.public.users-public"
jar: "transform-function-v1.jar"
parallelism: 2
retainOrdering: true
